inventory.yml.sample
The playbook errors out if we don't configure this.
=> Add ssh dir param to sample inventory

.github/workflows/ansible-lint.yml, .github/workflows/crucible-tests.yml
The official ansible-lint action disregards the .ansible-lint file
This runs the ansible linter from scratch, and also uses caching
to speed up execution.
=> update ansible-lint action

roles/setup_ntp/defaults/main.yml, roles/setup_ntp/templates/chrony.conf.j2
Made changes to the chrony.conf template to allow crucible to:
- set the listening address to `{{ ntp_server }}`.
- set a default listen address of 127.0.0.1
- allow from 127.0.0.1
- Cleaned up chrony.conf file
- Enables logging on the server.
=> Updating chrony.conf

roles/get_image_hash/defaults/main.yml, roles/get_image_hash/tasks/main.yml, roles/setup_assisted_installer/defaults/main.yml, roles/setup_assisted_installer/tasks/main.yml
* Fix the issue with release images having tags instead of digests which breaks disconnected installs
* By default only configure assisted installer to deploy the version of openshift which we are trying to deploy.
=> Release image digest and assisted installer versions config.

roles/insert_dns_records/tasks/network-manager.yml
On some RHEL/CentOS versions, dnsmasq isn't starting by NetworkManager after `systemctl restart NetworkManager` and resolv.conf is empty:
```
$ cat /etc/resolv.conf
```
dnsmasq is starting only after NetworkManager reload `systemctl restart NetworkManager` and adds the correct DNS server to resolv.conf:
```
$ cat /etc/resolv.conf
nameserver 127.0.0.1
```
I faced the issue on RHEL 8.5, [here](https://serverfault.com/questions/1054792/networkmanager-isnt-starting-dnsmasq-on-restart-only-reload) is a reference for the same issue on CentOS 7.9.
Adding reload task to make sure dnsmasq is starting.
=> Add NetworkManager reload for dnsmasq

roles/generate_discovery_iso/tasks/main.yml
When provisioning day2 worker nodes with static ip addresses, the
day2_worker group is not currently processed meaning these nodes
do not get an IP address. This commit fixes this.
=> Fix day2 worker node static ip addressing

roles/boot_disk/tasks/dell.yml
Fixed typo and updated name param to show iDrac version.
=> Typo in role/boot_disk/dell

README.md
It is not possible to cleanly install `kubectl` and `oc` on the bastion host given our current constraint of not requiring root on the bastion. In lieu of that, this add documentation of the requirement for them.
For an incomplete example of automating the install on the bastion, see https://github.com/redhat-partner-solutions/crucible/pull/58 which removes the `tar` install and therefore risks missing dependencies.
=> add openshift-clients to bastion dependencies

inventory.yml.sample, roles/display_deployment_plan/tasks/main.yml, roles/display_deployment_plan/templates/plan.j2
This change adds the following values to the plan's output:
- VIP DHCP Allocation (bool)
- Assisted Installer Setup (bool)
- Discovery ISO Name (string)
- Discovery ISO Download Path (string)
The output was updated to display the new path for ISOs, which from now on includes the cluster name in the path.
Signed-off-by: Marek Kochanowski <mkochanowski@redhat.com>
=> Extend deployment plan output with more details

docs/inventory.md
A couple of items are missing from the inventory sample for when
adding day 2 workers. This commit adds them.
=> Add examples for day 2 workers

roles/generate_ssh_key_pair/tasks/main.yml
The play failed after running. The reason for the failure is that the file already exists with different permissions because of being created by a different user running crucible.
The file is also copied to the home directory of the user and doesn't use the /tmp directory anymore.
I would like to add a task to delete the files from the tmp folder.
=> add Cleanup of /tmp/ssh_keys folder

docs/inventory.md, inventory.yml.sample, post_install.yml, roles/create_cluster/defaults/main.yml, roles/create_cluster/tasks/main.yml, roles/create_cluster/tasks/manifest.yml, roles/display_deployment_plan/tasks/main.yml, roles/display_deployment_plan/templates/plan.j2, roles/install_cluster/defaults/main.yml, roles/install_cluster/tasks/main.yml, roles/patch_host_config/defaults/main.yml, roles/patch_host_config/tasks/main.yml, roles/validate_inventory/defaults/main.yml, roles/validate_inventory/tasks/cluster.yml
From now on, end users can choose to deploy either a SNO or HA cluster.
SNO will be enabled automatically if and only if one master node and zero worker nodes are defined in the inventory.
Co-authored-by: Dylan Wong <dywong@redhat.com>
Signed-off-by: Marek Kochanowski <mkochanowski@redhat.com>
=> Add support for Single Node OpenShift deployments

playbooks/create_day2_cluster.yml, roles/create_day2_cluster/defaults/main.yml, roles/create_day2_cluster/tasks/main.yml, roles/create_day2_cluster/tasks/manifest.yml, roles/create_day2_cluster/templates/50-worker-nm-fix-ipv6.yml.j2, roles/create_day2_cluster/templates/50-worker-remove-ipi-leftovers.yml.j2, roles/create_day2_cluster/templates/patch-discovery-ignition.j2, roles/create_day2_cluster/templates/patch-install-config.j2, roles/create_day2_cluster/templates/patch-network-type.j2, roles/create_day2_cluster/templates/patch-search-registries.j2
Currently the day2 worker playbook is broken for disconnected installs
as the patching logic for mirrored registries does not exist. This
commit fixes this although its mostly a copy of the templates from
the main create cluster role so probably can be done a lot nicer.
Also, the CSR approval mechanism is still broken.
=> Fixes day2 worker playbook for disconnected installs

roles/boot_disk/tasks/hpe.yml, roles/boot_iso/tasks/hpe.yml
With community.general 3.5.0, redfish_command supports overriding
the boot mode so lets use that rather than the uri module. This
should apply to other hardware vendors but I only have access to
ILO to test currently.
=> Moves Ansible boot override mode to redfish_command

inventory.yml.sample, post_install.yml, roles/display_deployment_plan/tasks/main.yml, roles/display_deployment_plan/templates/plan.j2, roles/validate_inventory/tasks/required_vars.yml
Requires a new variable which `kubeadmin_vault_password_file_path` which defines the path to file containing the password for the vault
=> Save kubeadmin credentials to a ansible vault

roles/insert_dns_records/tasks/main.yml
Fixing a bug where day2 workers were not included in the loop when inserting DNS records
=> Including day2 workers when inserting dns records

roles/setup_sushy_tools/templates/sushy-tools.service.j2
You can set the `sushy_dir` variable, but the service file still pointed
to a static `/opt/sushy-tools` path.
=> Removing hard-coded sushy-tools path

roles/setup_http_store/tasks/main.yml
It seems there is an issue with later podman and its being
interpreted incorrectly. So we add quotes to ensure the colon
is part of the string.
=> Fixes issues with port parsing

deploy_prerequisites.yml
If using the network bridge specified in the virtual environment the dns
role will reference it before it's been created which will cause dnsmasq
to fail to run.  This will break all dns lookups until fixed.
This PR deploys the virtual resources before the dns role.
=> Deploy virtual network before dns

roles/create_vms/tasks/main.yml
This causes non-root user with sudo privileges to have the ability to create vms. Please review and let me know any further changes are required.
=> Provide non-root user the ability to create VMs

roles/populate_mirror_registry/tasks/populate_registry.yml, roles/populate_mirror_registry/tasks/prerequisites.yml
One of the requirements says to install the `openshift-clients` package,
which provides `/usr/bin/{kubectl,oc}`. Then when populating the
registry we download the binaries according to the version to be
installed, then overwrite them on top of the ones in `/usr/bin`. It's
probably better to keep the integrity of the RPM DB and install them to
`/usr/local/bin` instead.
=> Install manual binaries in /usr/local/bin

roles/setup_sushy_tools/tasks/main.yml, roles/setup_sushy_tools/templates/sushy-emulator.conf.j2
Instead of relying on redhat release version which doesn't work with
centos stream 8, check on the actual file existing instead.
=> Update logic in sushy-tools to use stat

roles/boot_iso/tasks/kvm.yml, roles/get_image_hash/tasks/get_image_hash.yml, roles/get_image_hash/tasks/main.yml, roles/populate_mirror_registry/defaults/main.yml, roles/populate_mirror_registry/tasks/populate_registry.yml, roles/populate_mirror_registry/tasks/prerequisites.yml, roles/validate_inventory/tasks/cluster.yml
Routinely, crucible only supports 1 "blessed" version from each major OCP branch. If you want to support release candidates and development builds, a few changes are needed.
Having these changes plus an inventory that looks something like this:
```yaml
assisted_service_openshift_versions_defaults:
"4.7":
release_version: 4.7.45
display_name: 4.7.45
support_level: production
release_image: "quay.io/openshift-release-dev/ocp-release@sha256:e2c1b0f7057d053045366b58566e81b0b11b92d95f67c8a3d4e8fd5b6e0a7f96"
rhcos_version: 47.84.202109241831-0
rhcos_image: "https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.7/47.84.202109241831-0/x86_64/rhcos-47.84.202109241831-0-live.x86_64.iso"
rhcos_rootfs: "https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/ …
```
=> Candidate and dev/nightly builds support

inventory.yml.sample
tftp_host is missing the : which invalidates the entire yaml file.
=> Fix syntax error in inventory sample

roles/process_nmstate/templates/nmstate.yml.j2
Minor update to allow fully isolated virt environments which we use for our CI setup.
With this patch we can specify the following in the hosts: -> vm_host1 section.
```yaml
network_config:
interfaces:
- type: linux-bridge
name: "{{ cluster_name }}-br"
addresses:
ipv4:
- ip: "{{ vm_bridge_ip }}"
prefix: "{{ machine_network_cidr | ipaddr('prefix') }}"
bridge:
stp: True
```
=> Naked bridge

roles/populate_mirror_registry/tasks/prerequisites.yml
Crucible will download OpenShift artifacts it needs, but it would be
better if it didn't do it for every run.
This is good for repeatable runs where you are testing the same
version(s) over and over again: downloaded artifacts will be reused as
a sort of cache.
=> Don't process existing OCP artifacts

docs/v1_to_v2_transition.md, roles/display_deployment_plan/tasks/main.yml, roles/display_deployment_plan/templates/plan.j2, roles/get_image_hash/defaults/main.yml, roles/get_image_hash/tasks/get_image_hash.yml, roles/get_image_hash/tasks/main.yml, roles/setup_assisted_installer/defaults/main.yml, roles/setup_assisted_installer/tasks/main.yml, roles/setup_assisted_installer/templates/pod.yml.j2
Hashes are now saved to a file in the repo root. If the
image key is already in the image_hashes saved we will not try
to get a new one. If you change version you expect to get you
may want to remove the value from the file or the file completely.
There is also a flag `ignore_cached_image_hashes` which will
ignore any save values and write a new file.
It is now much simpler to override the values in the os_images and
release_images as the format is now the same as assisted installer
expects. And there is no need to override as mean values as previous
just override os_images (if required), release_images and
supported_ocp_versions.
=> Add hash caching and simplify overriding assisted installer images

roles/validate_inventory/tasks/cluster.yml
If using an all digit mac address even when using the linux format ansible will
cast that into a mangled integer. Added an assert to alert the user of this
is happening and tell them to wrap the mac in quotes
=> Do regex to check mac is in linux format

roles/patch_host_config/tasks/main.yml
The task above (`Wait for up to 10 minutes for node discovery`) waits for the inventory however it will incorrectly set host to tasks result instead of the contents of the reply which is in the json attribute.
=> Fix error when fetching missing inventory

roles/insert_dns_records/tasks/main.yml
Pretty self explanatory, If bmc_dns_records isn't defined then don't try and process them.
=> Don't process bmc_dns_records if not defined

roles/get_image_hash/tasks/main.yml
You can specify the image as `$REGISTRY/$NS/$IMAGE:$TAG` but you can
also specify an image as `$REGISTRY/$NS/$IMAGE@$SHA_ALGO:$SHA_STR` e.g.
how they are set in `release.txt`: "Pull From: $IMAGE"
If the image is fully qualified then there will be an `@` character in
the URL, if that happens then there is no need to re-inspect the image
to get the signature.
=> Taking into account fully qualified image URLs

README.md, inventory.yml.sample, roles/get_image_hash/defaults/main.yml, roles/validate_inventory/defaults/main.yml, tests/validate_inventory/templates/all_reachable.yml, tests/validate_inventory/templates/all_unreachable.yml, tests/validate_inventory/templates/invalid_empty_var.yml, tests/validate_inventory/templates/invalid_missing_var.yml, tests/validate_inventory/templates/ntp_unreachable.yml, tests/validate_inventory/templates/test_inv.yml.j2, tests/validate_inventory/templates/test_inv_secrets.yml.j2
This PR:
(1) refreshes RHCOS base images used for both the 4.9 and 4.10 releases to a more recent version hosted on the OpenShift mirror site (mirror.openshift.com).  These represent 6 months of RHEL fixes and should be used as a base vs their older counterparts, as known problems have been observed in lab deployments with HA topologies.
(2) refreshes supported OpenShift versions to releases that contain rebases for `ice` and `iavf` 
drivers.  Customers and partners should also try to stay current with enhancements and security fixes present in these newer versions.
(3) update documentation to reflect support for both OpenShift 4.9 and 4.10, as well as links to public OpenShift documentation for the 4.10 release.
=> Refresh versions and RHCOS images

roles/get_image_hash/tasks/main.yml
Split only on the last colon not on the first as if there is a port in the url it will cause the resulting url to become incorrect
=> Fix bug with release image url splitting

roles/generate_discovery_iso/defaults/main.yml, roles/generate_discovery_iso/tasks/main.yml, roles/generate_discovery_iso/templates/patch-discovery-ignition-hostname-workground.j2, roles/generate_discovery_iso/templates/set-hostname-workaround.service.j2, roles/generate_discovery_iso/templates/set-hostname-workaround.sh.j2
When using static IPs network manager will do reverse dns lookups to set the
hostname of the node. When that node is the boot strap is can set the hostname
as api-int.<cluster_domain> when the api_vip bridge is brought up. This causes
and issue with the bootkube container as it uses --network=host, podman will
therefore insert the hostname of the host into containers /etc/hosts pointing
it to 127.0.1.1. If the kubeboot container starts before network manager, network manager
reverts the hostname (as the brige is removed) then the bootkube container
will be unable to communicate with the clusters kubeapi as it will be redirected
to 127.0.1.1 as per the /etc/hosts file. This causes the cluster installation
to fail.
To work around this issue crucible has a flag use_hostname_workaround
this …
=> Work around for network manager ordering race condition 

roles/setup_ntp/defaults/main.yml, roles/setup_ntp/templates/chrony.conf.j2
Defaults to [ntp_server_allow] if ntp_server_allow is defined.
This will be required to allow dual stack installations to communicate
with chrony. It will also be useful for more lab settings where multiple
clusters are being set up.
=> Add list ntp_server_allows

roles/insert_dns_records/defaults/main.yml, roles/validate_dns_records/defaults/main.yml
- Fixed var "domain" in validate_dns role.
- Made the var "domain" more legible in validate_dns and insert_dns.
=> validate_dns error var "domain" not found.

roles/display_deployment_plan/defaults/main.yml, roles/display_deployment_plan/tasks/main.yml, roles/display_deployment_plan/templates/plan.j2, roles/validate_inventory/tasks/validate_pxe.yml
- Fixed an issue where crucible crashes if setup_pxe_service is true and hosts:vendor is not set to pxe.
- The setup of the pxe service should not be tied to whether or not any host will use pxe.
=> Fix: no pxe hosts found.

roles/create_cluster/defaults/main.yml, roles/create_cluster/tasks/main.yml, roles/create_day2_cluster/defaults/main.yml, roles/create_day2_cluster/tasks/main.yml
It is now possible to override the default filenames using cluster_id_filename and day2_cluster_id_filename respectively
Note: I have made the defaults retain the previous behaviour.
=> Make cluster id filenames variables

roles/monitor_cluster/tasks/main.yml
It looks like the cluster installation failure message for an encountered error is copy-pasted improperly (it indicates `user cancelled` when the task itself is checking for a cluster error)
=> Fix installation fail msg in monitor_cluster role

roles/setup_sushy_tools/defaults/main.yml, roles/setup_sushy_tools/tasks/main.yml, roles/setup_sushy_tools/templates/sushy-tools.service.j2
Currently, sushy tools is installed in the system-wide python path, this causes issues with e.g. newer versions of libraries in the sushy releases, and overwriting RPM files with PIP files. Also adjusting the systemd service file to use the virtual environment.
=> Have sushy tools installed in a virtual env

roles/populate_mirror_registry/defaults/main.yml, roles/populate_mirror_registry/tasks/prerequisites.yml
This change started because it was needed to support OCP nightly builds, where `oc` client need to include the version before `.tar.gz`. Else, tests with assisted installer using nightly builds will fail, like in [this example](https://www.distributed-ci.io/jobs/9ae8ead2-2c6b-474b-a588-ed2c6f10cb87/jobStates?sort=date&task=e4753813-aa50-4dca-a107-fe365400e06a) that we have run in Telco CI labs.
The problem is, when having a nightly build, `release_url` is different (e.g. https://openshift-release-artifacts.apps.ci.l2s4.p1.openshiftapps.com/), and the way of interacting with these resources are a bit tricky, so they need to be handled in a different way.
In our dci-openshift-agent, we have already validated in [this change](https://softwarefactory-project.io/r/c/dci-openshift-agent/+/27122) …
=> Add support to OCP nightly builds for populate_mirror_registry/prerequisites

deploy_day2_workers.yml, deploy_prerequisites.yml, roles/add_day2_node/tasks/main.yml, roles/create_day2_cluster/tasks/main.yml, roles/destroy_vms/tasks/destroy_networks.yml, roles/destroy_vms/tasks/main.yml, roles/generate_discovery_iso/tasks/main.yml, roles/monitor_host/defaults/main.yml, roles/monitor_host/tasks/main.yml, roles/process_kvm_nodes/defaults/main.yml, roles/process_kvm_nodes/tasks/create_node.yml, roles/process_kvm_nodes/tasks/main.yml
This is becuase the day2 nodes maybe be added as a secondary run we must filter the kvm nodes otherwise the playbooks will destroy the current cluter.
=> Create day2 KVM nodes as part of day2 process

README.md, inventory.yml.sample, roles/get_image_hash/defaults/main.yml, roles/validate_inventory/defaults/main.yml, tests/validate_inventory/templates/all_reachable.yml, tests/validate_inventory/templates/all_unreachable.yml, tests/validate_inventory/templates/invalid_empty_var.yml, tests/validate_inventory/templates/invalid_missing_var.yml, tests/validate_inventory/templates/ntp_unreachable.yml, tests/validate_inventory/templates/test_inv.yml.j2, tests/validate_inventory/templates/test_inv_secrets.yml.j2
This PR:
(1) refreshes RHCOS base images used for the 4.9, 4.10, and 4.11 releases to a more recent version hosted on the OpenShift mirror site (mirror.openshift.com).  These represent four months of RHEL fixes and should be used as a base vs their older counterparts.
(2) refreshes supported OpenShift versions to align with respective RHCOS images.  Customers and partners should also try to stay current with enhancements and security fixes present in these newer versions.
(3) update documentation to reflect support for OpenShift 4.12 client tools.  OpenShift 4.12 needs to be tested before support is claimed in validate_inventory and in the README.
(4) validate_inventory tests version numbering is updated.
(5) switches arm from 4.10 to 4.12.
=> Refresh versions and RHCOS images Jan 2023

roles/create_cluster/defaults/main.yml, roles/create_cluster/tasks/main.yml, roles/patch_cluster/defaults/main.yml
Without workers masters have to schedulable so we will ignore the user provided parameter. Also removed manifest as it meant that the user var meant nothing as masters will always be schedulable regardless of the user's choice of value.
=> Only use schedulable_masters when cluster has workers

roles/post_install/tasks/main.yml
This allows for jq to read the creds easily making it easer to work with the kubeadmin vault
=> Make kubeadmin creds output in nice json

roles/insert_dns_records/templates/openshift-cluster.conf.j2, roles/mount_discovery_iso_for_pxe/defaults/main.yml
The Discovery ISO must have changed where the grub entries are found.  This updates to the new paths.
=> Update grub location for PXE installs

.github/workflows/crucible-tests.yml, requirements.yml, roles/insert_dns_records/tasks/main.yml, roles/insert_dns_records/templates/openshift-cluster.conf.j2, roles/setup_vm_host_network/defaults/main.yml, roles/validate_dns_records/tasks/main.yml, roles/validate_inventory/tasks/ai.yml, roles/validate_inventory/tasks/cluster.yml, roles/validate_inventory/tasks/dns.yml, roles/validate_inventory/tasks/ntp.yml
The changes requred to support RHEL 9 and ansible-core 2.11 where:
- use full name for ansible.utils.hwaddr
- use full name for ansible.utils.ipaddr
- update requirements.yml adding ansible.utils
=> Fix support for RHEL 9

roles/validate_inventory/tasks/cluster.yml
libvirt doesn't require the mac address to be upper case.   This changes the validation to accept both upper and lower.
=> Fix the check so it doesn't require uppercase hex

README.md, roles/get_image_hash/defaults/main.yml, roles/validate_inventory/defaults/main.yml
This PR:
(1) refreshes RHCOS base images used for the 4.12 release to a more recent version hosted on the OpenShift mirror site (mirror.openshift.com), from version 4.12.0 to version 4.12.3. These represent one month of RHEL fixes and should be used as a base vs their older counterparts.
(2) refreshes supported OpenShift versions for 4.12 to be 4.12.4, which is the latest stable version of 4.12 as of this authoring.  Several fixes in BMO & IPI, the RHEL kernel's iavf driver, etc, went in to address dual stack functionality gaps in 4.12.0 such as https://issues.redhat.com/browse/OCPBUGS-4895, and https://issues.redhat.com/browse/OCPBUGS-6015. Customers and partners should also try to stay current with enhancements and security fixes present in these newer versions of OpenShift Container …
=> update 4.12 versioning

roles/create_vms/defaults/main.yml, roles/create_vms/tasks/main.yml
We have found in our particular use case we don't want to login as the root user on the target VM Host but we also don't want the VMs to be created as some non-root user. This way we can set `ansible_user` to our non-root user and set `qemu_user` as root. The default (current) behavior stays the same.
=> Default the qemu_user to ansible user

docs/inventory.md
About the NICs status and DNS server IPs. These are important to keep in mind mostly when setting up a baremetal environment where all the interfaces are connected to some switch.
=> Added comments in inventory.md

roles/populate_mirror_registry/tasks/cleanup.yml, roles/populate_mirror_registry/tasks/main.yml, roles/populate_mirror_registry/tasks/populate_registry.yml, roles/populate_mirror_registry/tasks/prerequisites.yml
- Right now, we are placing all the binaries in `/usr/local/bin`
- It may happen that, if we are sharing the jumphost between multiple OCP clusters, this file path is common for all the deployments.
- It is better to have a dedicated folder for each deployment to save the binaries and use them whenever they are needed.
- Doing this in the populate_mirror_registry.
- Apart from this, we keep the `oc` and `kubectl` binaries in `/usr/local/bin` directories, since they are used in other roles. It is not the case of `opm` binary.
=> populate_mirror_registry | Use a tmp folder for oc/kubectl/opm binaries

roles/setup_http_store/defaults/main.yml
Sets the HTTP store container_image variable to
"quay.io/centos7/http-24-centos7:latest" since the current registry for
"registry.centos.org/centos/http-24-centos7:latest" was decommisioned on
June 7th, 2023. See [1].
[1] https://github.com/CentOS/container-index
=> Http store quay

inventory.yml.sample
I added the ocp 4.12.4 to the inventory sample because its in [supported_ocp_versions](https://github.com/redhat-partner-solutions/crucible/blob/main/roles/validate_inventory/defaults/main.yml)
=> Add 4.12.4 to the OpenShift version in inventory sample

roles/populate_mirror_registry/tasks/populate_registry.yml, roles/populate_mirror_registry/templates/filter.sh.j2
SQLite approch has been depricated so using the proceedure found here https://github.com/redhat-openshift-ecosystem/community-operators-prod/issues/793#issuecomment-1036213702
=> Update populate registry to use file based approch

roles/generate_manifests/defaults/main.yml, roles/generate_manifests/tasks/main.yml, roles/monitor_agent_based_installer/defaults/main.yml, roles/monitor_agent_based_installer/tasks/main.yml
- If installation fails, try to run `openshift-install gather bootstrap` command to retrieve logs from the bootstrap node (master-0)
- Backup agent-config files
=> Gather more Assisted logs

docs/inventory.md, roles/generate_manifests/defaults/main.yml, roles/generate_manifests/templates/install-config.yaml.j2, roles/validate_inventory/tasks/ai.yml
This change allows to pass extra VIPS for dualstack deployments using extra_api_vip and extra_ingress_vip variables.
Fixes: #261
=> add extra VIPs support for dualstack on OCP >= 4.12

README.md, inventory.yml.sample, roles/get_image_hash/defaults/main.yml, roles/validate_inventory/defaults/main.yml
This PR:
(1) makes a  specific note around not supporting RHEL9 based Bastion hosts, given internal testing.
(2) refreshes RHCOS base images used for the 4.11 and 4.12 releases to a more recent version hosted on the OpenShift mirror site (mirror.openshift.com). These represent three+ months of RHEL fixes and should be used as a base vs their older counterparts.
(3) refreshes supported OpenShift versions to align with respective RHCOS images. Customers and partners should also try to stay current with enhancements and security fixes present in these newer versions, vs staying on the same release for a long period of time.
(4) update documentation to reflect support for OpenShift 4.13 client tools. OpenShift 4.13 has been tested by teams to have support claimed in validate_inventory and in …
=> Refresh versions and RHCOS images Sep 2023

roles/setup_selfsigned_cert/tasks/main.yml
This reverts some of the changes included in https://github.com/redhat-partner-solutions/crucible/commit/c86104c6b1b6070043c4eccb9f18993430412484
While testing Assisted deployments with DCI on a daily basis, e.g. here: https://www.distributed-ci.io/jobs/68c4cb1f-0ff6-4a76-b6f0-4c2704c78214/jobStates?sort=date, we discovered that the usage of community.crypto is affecting the jobs, since it's not available for downloading through RPM. Its usage in DCI would depend on creating a custom RPM and inject it in the project, and that's something we would like to avoid unless it's unavoidable to use community.crypto.
Then, the proposal is to revert the usage of community.crypto in setup_selfsigned_cert.
=> Revert changes to use community.crypto collection in setup_selfsigned_cert

roles/install_cluster/defaults/main.yml, roles/install_cluster/tasks/main.yml
in order to make host discovery timeout configurable
=> introduce variable  hosts_discovery_minutes

roles/generate_agent_iso/tasks/main.yml, roles/generate_manifests/templates/registry-config.j2
- Modified: roles/generate_agent_iso/tasks/main.yml
- Moved the 'podman auth dir' from `config_file_path` to `generated_dir`.
- This allows the crucible user to create the required files without elevated permissions.
- Modified: roles/generate_manifests/templates/registry-config.j2
- Removed some templating that was changing imageContentSources into imageDigesstSources.
=> Abi testing rhel9

roles/setup_assisted_installer/defaults/main.yml, roles/setup_assisted_installer/templates/configmap.yml.j2
This PR proposes to add the local registry and set the access to that registry as insecure as first iteration to the assisted service container when using podman and not ABI in disconnected mode. The issue:
`podman logs -f assisted-installer-service`  prompts an x509 ca unknown authority because the certificate is not present inside the `assisted-installer-service` container
I may be missing details I'm not familiar with crucible code, please take a look.
**Do not merge.** We need to test this.
=> [DRAFT]: update role setup assisted installer configmap

docs/inventory.md
This PR:
1. updates an inventory example in the documentation to include proper naming.
https://issues.redhat.com/browse/OPNET-468 contains more background on why we should push customers to use the updated "port" nocmenclature.
https://www.redhat.com/en/blog/update-red-hats-conscious-language-efforts is also background on why this is important.
=> update inventory example with proper naming for port using NMstate

deploy_cluster.yml, deploy_day2_workers.yml, deploy_prerequisites.yml, playbooks/deploy_registry.yml, playbooks/populate_registry.yml, roles/display_deployment_plan/tasks/main.yml, roles/validate_inventory/tasks/ai.yml, roles/validate_inventory/tasks/day2.yml, roles/validate_inventory/tasks/dns.yml, roles/validate_inventory/tasks/main.yml, roles/validate_inventory/tasks/network.yml, roles/validate_inventory/tasks/ntp.yml, roles/validate_inventory/tasks/partitions.yml, roles/validate_inventory/tasks/prereqs.yml, roles/validate_inventory/tasks/proxy.yml, roles/validate_inventory/tasks/required_vars.yml, roles/validate_inventory/tasks/secrets.yml, roles/validate_inventory/tasks/validate_pxe.yml, roles/validate_inventory/tasks/vendor.yml, roles/validate_inventory/tasks/vms.yml, site.yml, tests/run_tests.yml, tests/validate_inventory/roles/run_suite/tasks/main.yml, tests/validate_inventory/roles/run_suite/tasks/run_test.yml, tests/validate_inventory/tests.yml
=> Fix ansible lint
