- playbooks/deploy_assisted_installer_onprem.yml
- playbooks/deploy_registry.yml
- roles/add_day2_node/tasks/main.yml
- roles/boot_disk/tasks/hpe.yml
- roles/boot_disk/tasks/kvm.yml
- roles/boot_iso/tasks/hpe.yml
- roles/boot_iso/tasks/kvm.yml
- roles/setup_assisted_installer/tasks/main.yml
- roles/validate_inventory/tasks/cluster.yml
> address linting issues

- README.md
> document sudo usage options

- docs/inventory.md
> add documentation for the VM uuid var

- roles/insert_dns_records/tasks/dnsmasq.yml
- roles/insert_dns_records/tasks/main.yml
> Fix dnsmasq missing when NetworkManager is used

- deploy_cluster.yml
Potential fix for https://github.com/redhat-partner-solutions/crucible/issues/96
> Fix check for generate_ssh_keys

- roles/create_cluster/tasks/main.yml
- roles/generate_ssh_key_pair/tasks/main.yml
- roles/install_cluster/tasks/main.yml
Potential fix for https://github.com/redhat-partner-solutions/crucible/issues/95
> Ensure 'fetched' dir exists before use

- docs/troubleshooting/assisted_installer_failing_to_fetch_iso.md
Added install bind-utils as it is not part of CentOS8 Appstream.
Changed dig to host as the output is easier to read.
> Troubleshooting update

- docs/inventory.md
- inventory.yml.sample
- roles/patch_host_config/defaults/main.yml
- roles/patch_host_config/tasks/main.yml
- roles/patch_host_config/templates/patch-worker-partition.j2
- roles/validate_inventory/tasks/main.yml
- roles/validate_inventory/tasks/partitions.yml
On branch main
Your branch is up to date with 'origin/main'.
Changes to be committed:
modified:   roles/patch_host_config/tasks/main.yml
new file:   roles/patch_host_config/templates/patch-worker-partition.j2
> Add ability to define partitions in ignition file.

- README.md
```
TASK [get_image_hash : Update hashes] ****************************************************************************************************************************************************************************************************************************************************************
Monday 21 March 2022  21:43:53 +0000 (0:00:06.594)       0:00:24.317 ********** 
fatal: [localhost]: FAILED! => 
msg: You need to install "jmespath" prior to running json_query filter
```
Fixed by:
```
$ sudo dnf install python3-jmespath
Updating Subscription Management repositories.
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs) …
```
> Add jmespath to prereqs

- README.md
- deploy_cluster.yml
- deploy_prerequisites.yml
- docs/inventory.md
- inventory.yml.sample
- playbooks/README.md
- playbooks/deploy_tftp.yml
- playbooks/mount_discovery_iso_for_pxe.yml
- roles/boot_iso/tasks/main.yml
- roles/boot_iso/tasks/pxe.yml
- roles/display_deployment_plan/tasks/main.yml
- roles/display_deployment_plan/templates/plan.j2
- roles/insert_dns_records/defaults/main.yml
- roles/insert_dns_records/tasks/configure_firewall.yml
- roles/insert_dns_records/templates/openshift-cluster.conf.j2
- roles/mount_discovery_iso_for_pxe/defaults/main.yml
- roles/mount_discovery_iso_for_pxe/tasks/main.yml
- roles/mount_discovery_iso_for_pxe/templates/grub.cfg.j2
- roles/setup_tftp/handlers/main.yml
- roles/setup_tftp/meta/main.yml
- roles/setup_tftp/tasks/main.yml
- roles/validate_inventory/defaults/main.yml
- roles/validate_inventory/tasks/main.yml
- roles/validate_inventory/tasks/validate_pxe.yml
Adding the feature of installing crucible with PXE service on bare metal servers 
fix #92
> Add pxe boot

- roles/insert_dns_records/defaults/main.yml
Add a default to tftp_host in TFTP_ROOT
> Remove the need to define a tftp_host

- playbooks/create_vms.yml
- playbooks/deploy_dns.yml
- playbooks/deploy_http_store.yml
- playbooks/deploy_ntp.yml
- playbooks/deploy_registry.yml
- playbooks/deploy_sushy_tools.yml
Small fix for gather_facts instruction. It now follows the conditions to trigger fact gathering.
> Fix gather_facts ignoring inventory variables

- .ansible-lint
- post_install.yml
- roles/apply_nmstate/tasks/main.yml
- roles/approve_csrs/tasks/main.yml
- roles/create_vms/tasks/provision_vms.yml
- roles/destroy_vms/tasks/destroy_vms.yml
- roles/get_image_hash/tasks/main.yml
- roles/mount_discovery_iso_for_pxe/tasks/main.yml
- roles/populate_mirror_registry/tasks/populate_registry.yml
- roles/populate_mirror_registry/tasks/prerequisites.yml
- roles/setup_assisted_installer/tasks/main.yml
- roles/setup_selfsigned_cert/tasks/main.yml
- roles/setup_sushy_tools/tasks/main.yml
- roles/validate_inventory/tasks/vms.yml
Issues are listed here https://github.com/nocturnalastro/crucible/runs/6126261622?check_suite_focus=true
> Fixing linting issues

- inventory.yml.sample
- roles/create_day2_cluster/defaults/main.yml
- roles/create_day2_cluster/tasks/main.yml
- roles/patch_cluster/defaults/main.yml
- roles/setup_assisted_installer/defaults/main.yml
- roles/setup_assisted_installer/templates/configmap.yml.j2
Set and populate proxy seettings in:
- Inventory
- AI config
- Day2 clusters config
Also remove unused proxy settings from the patch_cluster role.
Addresses https://github.com/redhat-partner-solutions/crucible/issues/148
> Fix proxy settings

- requirements.yml
5.x does not support ansible 2.9 - https://github.com/ansible-collections/community.general/pull/4548
> Pin community.general version for ansible 2.9

- CONTRIBUTING.md
Making minor grammatical and spelling changes to improve the readability of CONTRIBUTING.md
> Proofing of CONTRIBUTING.md

- roles/generate_discovery_iso/templates/patch-discovery-ignition.j2
- roles/install_cluster/defaults/main.yml
- roles/install_cluster/tasks/main.yml
- roles/setup_assisted_installer/tasks/main.yml
Make install cluster more robust by allowing cluster the cluster state to be updated before the check.
> More robust install cluster and small fixes

- roles/display_deployment_plan/templates/plan.j2
Jinja was complaining that there was an unexpected end block removing the else and switching the +s for -s seems to have removed the issue
> Fix issue with deployment plan template

- ansible.cfg
- deploy_prerequisites.yml
- requirements.txt
- reordered deploy_registry.yml to run after deploy_dns.yml
> Updated deploy_prerequisites.yml

- roles/patch_cluster/defaults/main.yml
- roles/patch_cluster/tasks/manifest.yml
Also requires slight change if people have be overriding manifest templates
> Add ability for users to more neatly apply custom manifests

- .github/ISSUE_TEMPLATE/bug-report.yml
- README.md
- roles/generate_discovery_iso/defaults/main.yml
- roles/get_image_hash/defaults/main.yml
- roles/validate_inventory/defaults/main.yml
This is the value being used for ai_version by the DCI team
> Bump assisted installer version to v2.12.1

- roles/apply_nmstate/tasks/main.yml
ansible is erroring with "invalid filter deinfed"
> Fixing tiny typo

- roles/generate_discovery_iso/tasks/main.yml
- roles/setup_assisted_installer/defaults/main.yml
- roles/setup_assisted_installer/templates/pod.yml.j2
- roles/validate_http_store/tasks/main.yml
- roles/vendors/kvm/tasks/iso.yml
* Increasing the timeout when inserting the virtual media iso
* Correctly labeling the http content for SELinux
* Adding ability to mount host volumes on the assisted installer pods
> Improvements found on KVM testing

- README.md
- roles/generate_agent_iso/tasks/main.yml
> make sure nmstate is installed before generating ISO

- inventory.yml.sample
vm_network_test_ip parameter addition at inventory.yml due to task : Check if vm_host is bastion
> vm_network_test_ip parameter addition at inventory.yml

- README.md
- roles/generate_manifests/defaults/main.yml
- roles/generate_manifests/templates/registry-config.j2
- roles/patch_cluster/defaults/main.yml
- roles/patch_cluster/templates/patch-install-config.j2
> add support for imageDigestSources in disconnected OCP >= 4.14

- README.md
Updated the README to reflect upcoming role deprecation and added a line to install the redhatci.ocp collection.
> Updating README.md to reflect upcoming role deprecation.

- README.md
- Added sunset date
- Added notice of upcoming role changes
- Added notice of upcoming installer changes
- Fixed up linting issues
> Updated README with sunset info.
